'use strict';
const ideas=[
{id:'pausa',category:'calma',tag:'UN MOMENTO PARA TI',title:'Haz una pausa. Vuelve a ti.',description:'Regálate un minuto para soltar el ruido y disfrutar del presente.',time:'1 min',audience:'A tu ritmo',image:'photo-1472396961693-142e6e269027',alt:'Un rincón de bosque verde y tranquilo',steps:['Busca una posición cómoda y deja descansar tus manos.','Respira a tu ritmo, sin forzarte. Observa los sonidos que te rodean.','Cuando termine el minuto, elige una sola cosa a la que quieras dedicar tu atención.']},
{id:'aprender',category:'aprender',tag:'SIEMPRE HAY ALGO NUEVO',title:'La curiosidad no tiene edad.',description:'Convierte una pregunta cotidiana en un pequeño descubrimiento.',time:'10 min',audience:'Todas las edades',image:'photo-1455390582262-044cdead277a',alt:'Un cuaderno abierto para escribir nuevas ideas',steps:['Anota una pregunta sobre algo que hayas visto hoy.','Busca la respuesta en un libro o una fuente educativa. Comprueba quién la publica y de dónde viene la información.','Escribe lo que aprendiste con tus propias palabras y una nueva pregunta para mañana.']},
{id:'familia',category:'compartir',tag:'EL VALOR DE ESTAR JUNTOS',title:'Un ratito que nos acerque.',description:'Una conversación diferente con las personas que quieres, sin pantallas de por medio.',time:'15 min',audience:'En compañía',image:'photo-1511632765486-a01980e01a18',alt:'Una familia que comparte un momento al aire libre',steps:['Invita a alguien a compartir un rato tranquilo. Puede ser en persona o por teléfono.','Pregunten por turnos: «¿qué recuerdo te hace sonreír?» y «¿qué te gustaría aprender?».','Escuchen sin interrumpir. Cualquiera puede pasar una pregunta si lo prefiere.','Elijan una actividad pequeña que les gustaría hacer juntos esta semana.']},
{id:'gratitud',category:'calma',tag:'MIRAR LO COTIDIANO',title:'Tres cosas que hicieron bien.',description:'Reconoce los detalles que dieron un poco de luz a tu día.',time:'5 min',audience:'A tu ritmo',image:'photo-1441974231531-c6227db76b6e',alt:'Luz entre los árboles',steps:['Piensa en tres momentos agradables de hoy, por pequeños que sean.','Anota una palabra para cada uno en un papel.','Elige uno que te gustaría repetir mañana. Si hoy fue difícil, basta con reconocer algo que te ayudó a seguir.']},
{id:'historia',category:'compartir',tag:'APRENDER ENTRE GENERACIONES',title:'Una historia que merece quedarse.',description:'Descubre una anécdota de alguien cercano y dale un lugar en tu memoria.',time:'20 min',audience:'En compañía',image:'photo-1455390582262-044cdead277a',alt:'Papel para guardar una historia familiar',steps:['Pide a alguien que te cuente cómo era un día de su infancia.','Pregunta por un juego, una comida o una persona que recuerde con cariño.','Si quiere, escriban juntos la historia. Pide permiso antes de grabarla o compartirla.']},
{id:'palabra',category:'aprender',tag:'UN PEQUEÑO DESCUBRIMIENTO',title:'Una palabra, una nueva mirada.',description:'Aprende una palabra nueva y encuentra una forma de usarla hoy.',time:'5 min',audience:'Todas las edades',image:'photo-1455390582262-044cdead277a',alt:'Cuaderno con espacio para aprender una palabra',steps:['Abre un libro y encuentra una palabra cuyo significado no conozcas.','Consúltala en un diccionario y escribe su significado con tus palabras.','Inventa una frase donde la usarías y léela en voz alta.']}
];
const $=id=>document.getElementById(id);let filter='all',current=null,timer=null;
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
let tasks=read('uniluva-day',[]);if(!Array.isArray(tasks))tasks=[];tasks=tasks.filter(t=>t&&typeof t.text==='string'&&typeof t.id==='string').map(t=>({...t,done:!!t.done}));
function save(){try{localStorage.setItem('uniluva-day',JSON.stringify(tasks));$('storage-status').textContent=''}catch{$('storage-status').textContent='No se pudo guardar en este navegador. Tus cambios estarán disponibles mientras mantengas la página abierta.'}}
function normalize(s){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase()}
function renderCards(){const query=normalize($('search').value.trim());const list=ideas.filter(i=>(filter==='all'||i.category===filter)&&normalize(i.title+' '+i.description+' '+i.category+' '+i.id+' '+i.audience).includes(query));const shown=filter==='all'&&!query?list.slice(0,3):list;$('cards').replaceChildren();for(const idea of shown){const card=document.createElement('article');card.className='idea-card';card.innerHTML=`<div class="card-picture"><img src="https://images.unsplash.com/${idea.image}?auto=format&fit=crop&w=700&q=80" alt="${idea.alt}" loading="lazy"></div><div class="card-content"><span class="card-tag">${idea.tag}</span><h3>${idea.title}</h3><p>${idea.description}</p><div class="card-bottom"><span>${idea.time} · ${idea.audience}</span><button type="button">Explorar ↗</button></div></div>`;card.querySelector('button').setAttribute('aria-label','Explorar: '+idea.title);card.querySelector('button').onclick=()=>openIdea(idea);$('cards').append(card)}$('empty').hidden=!!shown.length}
document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{filter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>{const selected=b===button;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected))});renderCards()});$('search').addEventListener('input',renderCards);
function renderTasks(){$('tasks').replaceChildren();for(const task of tasks){const li=document.createElement('li'),label=document.createElement('label'),check=document.createElement('input'),span=document.createElement('span'),remove=document.createElement('button');check.type='checkbox';check.checked=task.done;span.textContent=task.text;check.onchange=()=>{task.done=check.checked;save();renderTasks()};remove.textContent='×';remove.setAttribute('aria-label','Eliminar: '+task.text);remove.onclick=()=>{tasks=tasks.filter(t=>t.id!==task.id);save();renderTasks()};label.append(check,span);li.append(label,remove);$('tasks').append(li)}const n=tasks.filter(t=>!t.done).length;$('task-count').textContent=n+' pendiente'+(n===1?'':'s');$('tasks-empty').hidden=tasks.length>0}
function addTask(text){tasks.push({id:globalThis.crypto?.randomUUID?.()||String(Date.now()+Math.random()),text,done:false});save();renderTasks()}
$('task-form').onsubmit=e=>{e.preventDefault();const text=$('task-input').value.trim();if(!text)return;addTask(text);$('task-input').value='';$('task-input').focus()};
function stopPause(){clearInterval(timer);timer=null;$('pause-clock').textContent='01:00';$('pause-label').textContent='Un minuto para bajar el ritmo.';$('pause-start').textContent='Comenzar pausa'}
function openIdea(idea){current=idea;stopPause();$('detail-category').textContent=idea.tag;$('detail-title').textContent=idea.title;$('detail-intro').textContent=idea.description;$('detail-steps').replaceChildren(...idea.steps.map(s=>{const li=document.createElement('li');li.textContent=s;return li}));$('pause-tool').hidden=idea.id!=='pausa';$('idea-status').textContent='';$('detail').showModal()}
$('close-dialog').onclick=()=>$('detail').close();$('detail').addEventListener('close',stopPause);$('detail').addEventListener('click',e=>{if(e.target===$('detail')){const r=$('detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('detail').close()}});
$('add-idea').onclick=()=>{if(current){if(!tasks.some(t=>t.text===current.title&&!t.done))addTask(current.title);$('idea-status').textContent='Listo. Encontrarás esta idea en Mi día.'}};
$('pause-start').onclick=()=>{if(timer){stopPause();return}const end=Date.now()+60000;$('pause-clock').textContent='01:00';$('pause-start').textContent='Detener pausa';$('pause-label').textContent='Respira a tu ritmo. Este momento es tuyo.';timer=setInterval(()=>{const remaining=Math.max(0,Math.ceil((end-Date.now())/1000));$('pause-clock').textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');if(!remaining){clearInterval(timer);timer=null;$('pause-label').textContent='Tu pausa ha terminado. Continúa a tu ritmo.';$('pause-start').textContent='Repetir pausa'}},250)};
let large=read('uniluva-large-text',false)===true;function setText(){document.documentElement.classList.toggle('large-text',large);$('text-size').setAttribute('aria-pressed',String(large));$('text-size').setAttribute('aria-label',large?'Desactivar texto grande':'Activar texto grande')}setText();$('text-size').onclick=()=>{large=!large;setText();try{localStorage.setItem('uniluva-large-text',JSON.stringify(large))}catch{}};
renderCards();renderTasks();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});
